name: github pages

on:
  push:
    branches:
    - source

jobs:
  build-deploy:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2

    - name: Deploy ðŸš€
      uses: chabad360/hugo-gh-pages@master
      with:
        githubToken: ${{ secrets.DEPLOY_TOKEN }}
        cname: www.behavioral-ds.ml
        branch: main
        hugoVersion: extended_0.60.1
        
    - name: Webhook on failure
      if: ${{ failure() }}
      uses: rtCamp/action-slack-notify@v2
      env:
        SLACK_COLOR: ${{ job.status }}
        SLACK_ICON: https://github.com/github.png?size=48
        SLACK_MESSAGE: 'Failed to deploy'
        SLACK_TITLE: Fail!
        SLACK_USERNAME: GitHub
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
